export enum SOCKET_CHANNELS {
    JOIN = 'JOIN',
    JOIN_CHAT = 'JOIN_CHAT',
    SEND_MESSAGE = 'SEND_MESSAGE',
    RECEIVE_MESSAGE = 'RECEIVE_MESSAGE',
    SEND_NOTIFICATION = 'SEND_NOTIFICATION',
    RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION',
}

export enum USER_ROOM {
    ADMIN_ROOM = 'ADMIN_ROOM',
    SELLER_ROOM = 'SELLER_ROOM',
    BUYER_ROOM = 'BUYER_ROOM',
}

export enum USER_ROLE {
    ADMIN = 'ADMIN',
    SELLER = 'SELLER',
    BUYER = 'BUYER',
}

export enum CHAT_TYPE {
    NORMAL_CHAT = 'NORMAL_CHAT',
    REFUND_CHAT = 'REFUND_CHAT',
    ADMIN_CHAT = 'ADMIN_CHAT',
}

export enum NOTIFICATION_TARGET {
    All = 'ALL',
    BUYER = 'BUYER',
    SELLER = 'SELLER',
    ADMIN = 'ADMIN',
}

export enum CHATROOM_STATUS {
    OPENED = 'OPENED',
    CLOSED = 'CLOSED',
}